name: Draw Owl

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  TRIGGER_WORD: 4LLM


# https://github.com/actions/runner/issues/662
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.early.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: early
        name: Branch check
        # https://stackoverflow.com/questions/229551/how-to-check-if-a-string-contains-a-substring-in-bash
        run: |
          status="skip"
          if [[ "${{ github.event.head_commit.message }}" == *$TRIGGER_WORD ]]
          then
            status="execute"
          fi
          echo $status

          echo "status=$status" >> $GITHUB_OUTPUT

  complete_code:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'execute'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check commit message
      run: |
        if [[ ! "${{ github.event.head_commit.message }}" =~ $TRIGGER_WORD ]]; then
          echo "Commit message does not contain trigger word. Skipping job."
          exit 0
        fi
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install omegaconf openai
      
    - name: Run draw_owl.py
      run: python draw_owl.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: LLM auto-completed.
        branch: llm-autocompletion
        branch-suffix: timestamp
